version: 0.1

phases:
  install:
    commands:
      - echo Install1 started on `date`
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - sh gradlew --debug --stacktrace build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/aws-app-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - runapp.sh
  discard-paths: yes